name: run eventos.sh

on:
  workflow_dispatch:
  
  schedule:
    # Corre cada 1h
    #- cron: '0 * * * *'
    # Otras programaciones
    - cron: '0,15,30,45 8-23 * * *'
    #- cron: '0 0-10/3 * * *'
    # Corre cada 2h    
    #- cron: '0 */2 * * *'
    # Test
    #- cron: '15,45 10-23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push
      contents: write
      
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: Instalar tor
        run: sudo apt-get install tor -y
  
      - name: Instalar curl
        run: sudo apt-get install curl -y
  
      - name: Instalar pandoc
        run: sudo apt-get install pandoc -y

      - name: Ejecutar script eventos.sh
        run: |
          chmod +x eventos.sh
          ./eventos.sh
          
       - name: pull changes
          run: git pull
      - name: commit files origin eventos
      
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update list" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
